### ISSUE TITLE
Tracking issue: deprecation and removal of `cookie` option

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#371]
This tracks deprecation and removal of `cookie` option which was confusing.

- [x] Implement deprecation of `cookie` - warning in the code and explanation in docs (#360)
- [x] Release a version with deprecation
- [x] Turn warning into hard error
- [x] Remove all code handling `cookie` option

**Comment by Kixunil** [comment]
@romanz Do we want to do last two steps as one in 0.9 or should we revert warning removal and turn it into error?

**Comment by romanz** [comment]
Let's drop `cookie` in `0.9.0-rc1` - so the user will get the following error:
```
Error: An unknown argument '--cookie' was specified
```
WDYT?

**Comment by Kixunil** [comment]
Yeah, originally I intended for it to be more clearly state that this argument was known in the past but was removed and point to docs. But if you think it's not worth the effort I'm fine with it being removed entirely (which it currently is).

**Comment by romanz** [comment]
You're right, let's add an explicit failure in case `cookie` is specified at 0.8.12 -> #478

**Comment by romanz** [comment]
0.8.12 will be released soon: #480

**Comment by Kixunil** [comment]
So effectively 0.8.12 only disables cookie and has no other change. Does it make sense to release it?

**Comment by romanz** [comment]
It would be the last (and the smallest ever) 0.8.x release :)

**Comment by romanz** [comment]
IIUC, this issue can be closed since there is no `cookie`-relevant code left in `master` :)

**Comment by Engelberg** [comment]
I have never used the cookie option, nor do I have a cookie file, but when I upgraded to version 0.9.4, I get the following error:

```
Error: electrs failed

Caused by:
    0: failed to open bitcoind cookie file: /home/mark/.bitcoin/.cookie
    1: No such file or directory (os error 2)
```

**Comment by romanz** [comment]
Could you please check that `bitcoind` is running?

**Comment by Engelberg** [comment]
bitcoind is running, but it looks like maybe it's trying to reach it at port 8333, possibly not respecting my flag --daemon-rpc-addr=127.0.0.1:28256. Has that configuration option changed recently?

**Comment by Engelberg** [comment]
Ah, I see port 8333 is the p2p port not the rpc port. I don't know why it would be having trouble reaching that, but that does seem to be a factor here. I will keep poking around.

**Comment by Engelberg** [comment]
Needed to set the daemon_p2p_addr. Not sure what changed between versions, but this fixed my problem.

**Comment by romanz** [comment]
Latest release is using both `p2p` port for fetching blocks (8333) and `rpc` port (8332) for the rest :)

**Comment by divinationstar** [comment]
Has this cookie issue been resolved? I'm getting the cookie error message after running ./target/release/electrs even if I remove the cookie entry in config.toml. I'm doing a new install.

Error: electrs failed

Caused by:
    0: failed to open bitcoind cookie file: /root/.bitcoin/.cookie
    1: No such file or directory (os error 2)

**Comment by Kixunil** [comment]
@divinationstar your configuration/system is somehow broken. Either the path is wrong or you don't have permissions (and FS pretends it doesn't exist) or bitcoind is not running. I'm practically certain electrs code is correct.

Also running stuff like this under root is probably a bad idea...

**Comment by divinationstar** [comment]
Will start from scratch. Any suggestions on what I can change to get it to install properly?

**Comment by Kixunil** [comment]
My recommendation is to simply not use ordinary users and either run both bitcoind and electrs under system user or stick [btc-rpc-proxy](https://github.com/Kixunil/btc-rpc-proxy/) between them. Or consider using [Debian packages](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder) which do the whole setup automatically without you having to debug these issues and figure out how to handle security.

**Comment by TylonHH** [comment]
It's hard to solve this when using umbrel. It seems that they generate the .cookie file. I opened issues on github, umbrel, [discord](https://discord.com/channels/936694604231766046/1343548993963167825), blocktrainer.
But no one can tell my within umbrel how to tell electrs to use the rpc from BTC.

**Comment by Kixunil** [comment]
@TylonHH sorry, that's not our issue. They use some docker setup and docker certainly allows passing that information in reasonable ways, so it's also not some kind of problem with our APIs. You need to ask them to help you or, if they are unable to, consider using an alternative node solution that just works out of the box.
